repos:

  # GENERIC
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        name: Check Added Large Files
        description: Prevents large files from being committed
        args:
          - --maxkb=1000
      - id: check-builtin-literals
        name: Check Builtin Literals
        description: Ensures builtin literals are used correctly
      - id: check-case-conflict
        name: Check Case Conflict
        description: Detects files with names differing only in case
      - id: check-executables-have-shebangs
        name: Check Executables Have Shebangs
        description: Ensures executable scripts have a shebang line
      - id: check-illegal-windows-names
        name: Check Illegal Windows Names
        description: Prevents files with names illegal on Windows
      - id: check-merge-conflict
        name: Check Merge Conflict
        description: Detects merge conflict markers
        args:
          - --assume-in-merge
      - id: check-shebang-scripts-are-executable
        name: Check Shebang Scripts Are Executable
        description: Ensures scripts with shebangs are executable
      - id: check-symlinks
        name: Check Symlinks
        description: Ensures symlinks are valid
      - id: check-toml
        name: Check TOML
        description: Checks TOML files for syntax errors
      - id: check-vcs-permalinks
        name: Check VCS Permalinks
        description: Prevents VCS permalinks in code
      - id: debug-statements
        name: Debug Statements
        description: Prevents debug statements from being committed
      - id: destroyed-symlinks
        name: Destroyed Symlinks
        description: Detects destroyed symlinks
      - id: detect-private-key
        name: Detect Private Key
        description: Prevents committing private keys
      - id: end-of-file-fixer
        name: End of File Fixer
        description: Ensures exactly one newline at EOF
      - id: trailing-whitespace
        name: Trailing Whitespace
        description: Removes accidental spaces at end of lines

  # TERRAFORM
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.103.0"
    hooks:
      - id: terraform_fmt
        name: Terraform - Formatter
        description: Formats Terraform files
      - id: terraform_validate
        name: Terraform - Validator
        description: Validates Terraform configuration
      - id: terraform_tflint
        name: Terraform - TFLint
        description: Lints Terraform files with TFLint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
